version: '3.7'

services:
  web-search-service:
    image: web-search-service:latest
    container_name: web-search-service
    ports:
      - "8086:8086"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2g'
    networks:
      - web_monitoring_network
    depends_on:
      - web-prometheus

  web-shopping-service:
    image: web-shopping-service:latest
    container_name: web-shopping-service
    ports:
      - "8087:8087"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2g'
    networks:
      - web_monitoring_network
    depends_on:
      - web-prometheus

  web-order-service:
    image: web-order-service:latest
    container_name: web-order-service
    ports:
      - "8088:8088"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2g'
    networks:
      - web_monitoring_network
    depends_on:
      - web-prometheus

  web-shop-mock-service:
    image: shop-mock-service:latest
    container_name: web-shop-mock-service
    ports:
      - "8082:8082"
    networks:
      - web_monitoring_network
    depends_on:
      - web-prometheus

  web-prometheus:
    image: prom/prometheus:latest
    container_name: web-prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - web_monitoring_network
    depends_on:
      - web-grafana

  web-grafana:
    image: grafana/grafana:latest
    container_name: web-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - web_monitoring_network

  web-cadvisor:
    image: google/cadvisor:latest
    container_name: web-cadvisor
    command:
      - '--housekeeping_interval=10s'
      - '--max_housekeeping_interval=15s'
      - '--allow_dynamic_housekeeping=true'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - web_monitoring_network

  web-mongodb:
    image: mongo
    container_name: web-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=shopping
    ports:
      - "27017:27017"
    networks:
      - web_monitoring_network
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  web-mongo-express:
    image: mongo-express
    container_name: web-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: web-mongodb
    depends_on:
      - web-mongodb
    networks:
      - web_monitoring_network

networks:
  web_monitoring_network:
    driver: bridge
